config/routes.rb
Rails.application.routes.draw do
  root 'users#top'
  resources :sessions, only: [:new, :create, :destroy, :show]
  resources :favorites, only: [:create, :destroy]
  resources :restaurants
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  include SessionsHelper
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :favorites, dependent: :destroy
    belongs_to :user
    has_many :favorite_users, through: :favorites, source: :user
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
    mount_uploader :image, ImageUploader
    validates :name, presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 255 },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    before_save { email.downcase! }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    has_many :favorites, dependent: :destroy
    has_many :restaurants, dependent: :destroy
    has_many :favorite_restaurants, through: :favorites, source: :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  
  def current_user_login
      unless  current_user
      flash[:referer] = 'ログインしてください'
      # render new_session_path URLと同じにする
      redirect_to new_session_path
      end
  end    
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
      favorite = current_user.favorites.create(restaurant_id: params[:restaurant_id])
      redirect_to restaurants_url, notice: "#{favorite.restaurant.user.name}さんのブログをお気に入り登録しました"
  end 
  def destroy
	    favorite = current_user.favorites.find_by(restaurant_id: params[:restaurant_id]).destroy
	    redirect_to restaurants_url, notice: "#{favorite.restaurant.user.name}さんのブログのお気に入りを解除しました"
  end 
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :current_user_login, only: [:new, :edit, :show, :index, :destroy]


  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @favorite = current_user.favorites.find_by(restaurant_id: @restaurant.id)
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user_id = current_user.id

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:image, :name, :place, :user_id)
    end
    
    def current_user_login  #
     unless  current_user
      flash[:referer] = 'ログインしてください'
      render new_session_path
     # redirect_to new_session_path          render? redirect?
     
     end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました' 
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :current_user_login, only: [:edit, :show, :index]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @favorite_restaurants = @user.favorite_restaurants #アソシエーション名
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        ContactMailer.contact_mail(@user).deliver
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :image, :password, :password_confirmation)
    end

  def current_user_login
   unless  current_user
    # flash[:referer] = 'ログインしてください'
    render new_session_path
   end
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user 
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
        !current_user.nil?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dorasute</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
    　<%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
      <%= link_to "私のお気に入り", user_path(current_user.id) %>
      <%= link_to '食事処一覧', restaurants_path %>
    <% else %>
      <%= link_to "新規登録", new_user_path %>
      <%= link_to "ログイン", new_session_path %>
    <% end %>
    
    
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :restaurant_image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :restaurant_name %>
  </div>

  <div class="field">
    <%= form.label :place %>
    <%= form.text_field :place, id: :restaurant_place %>
  </div>

  <!--<div class="field">-->
  <!--  <%#= form.label :user_id %>-->
  <!--  <%#= form.number_field :user_id, id: :restaurant_user_id %>-->
  <!--</div>-->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Place</th>
      <th>投稿者</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= image_tag(restaurant.image) %></td>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.place %></td>
        <td><%= restaurant.user.name %></td>
        <td><%= link_to 'Show', restaurant %></td>
        
        <% if current_user  == @user %>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= image_tag @restaurant.image %>
</p>

<p>
  <strong>店名</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Place:</strong>
  <%= @restaurant.place %>
</p>

<p>
  <strong>投稿者</strong>
  <%=  @restaurant.user.name %>
</p>

<% unless @restaurant.user == current_user %>

  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(restaurant_id: @restaurant.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(restaurant_id: @restaurant.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>



<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :user_image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>
  
  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :user_password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Image</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.image %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>新規登録</h1>

<%= render 'form', user: @user %>

<%= link_to '戻る', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<h2>お気に入り一覧</h2>
<p>
  <strong>Image:</strong>
  <%= image_tag @user.image, class: 'user_image' %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>


<% @user.favorite_restaurants.each do |restaurant| %>
<ol>
    <li>店名：<%= restaurant.name %>場所：<%= restaurant.place %></li>
</ol>


<% end %>


<%= link_to '食事処を探す', restaurants_path %>


<%= link_to 'Edit', edit_user_path(@user) %> 
<%= link_to 'Back', users_path %>

app/views/users/top.html.erb
<div class="container">
    <body id = "introduce">
            <h3>ドライブステーション</h3>
            <P>大型車でも立ち寄り出来るお風呂と食事処の情報ページです</p>
             <!--<a class="btn btn-primary btn-lg" href="new_user" role="button">スタート»</a>-->
             <p><%= link_to "スタート", new_user_path %></p>
    </body>
</div>